covid19_country_name_map = {
    '不丹': 'Bhutan',
    '东帝汶': 'Tinor-Leste',
    '中国': 'China',
    '中非共和国': 'Central African Republic',
    '丹麦': 'Denmark',
    '乌克兰': 'Ukraine',
    '乌兹别克斯坦': 'Uzbekstan',
    '乌干达': 'Uganda',
    '乌拉圭': 'Uruguay',
    '乍得': 'Chad',
    '也门共和国': 'The Republic of Yemen',
    '亚美尼亚': 'Armenia',
    '以色列': 'Israel',
    '伊拉克': 'Iraq',
    '伊朗': 'Iran',
    '伯利兹': 'Belize',
    '佛得角': 'Cabo Verde',
    '俄罗斯': 'Russia',
    '保加利亚': 'Bulgaria',
    '克罗地亚': 'Croatia',
    '关岛': 'Guam',
    '冈比亚': 'Gambia',
    '冰岛': 'Iceland',
    '几内亚': 'Guinea',
    '几内亚比绍': 'Guinea Bissau',
    '列支敦士登': 'Liechtenstein',
    '刚果（布）': 'Congo',
    '刚果（金）': 'Democratic Republic of the Congo',
    '利比亚': 'Libya',
    '利比里亚': 'Liberia',
    '加拿大': 'Canada',
    '加纳': 'Ghana',
    '加蓬': 'Gabon',
    '匈牙利': 'Hungary',
    '北马其顿': 'North Macedonia',
    '北马里亚纳群岛联邦': 'Northern Mariana Islands',
    '南苏丹': 'South Sudan',
    '南非': 'Republic of South Africa',
    '博茨瓦纳': 'Botswana',
    '卡塔尔': 'Qatar',
    '卢旺达': 'Rwanda',
    '卢森堡': 'Luxembourg',
    '印度': 'India',
    '印度尼西亚': 'Indonesia',
    '危地马拉': 'Guatemala',
    '厄瓜多尔': 'Ecuador',
    '厄立特里亚': 'Eritrea',
    '叙利亚': 'Syria',
    '古巴': 'Cuba',
    '吉尔吉斯斯坦': 'Kyrgyzstan',
    '吉布提': 'The Republic of Djibouti',
    '哈萨克斯坦': 'Kazakhstan',
    '哥伦比亚': 'Colombia',
    '哥斯达黎加': 'Costa Rica',
    '喀麦隆': 'Cameroon',
    '土库曼斯坦': 'Turkmenistan',
    '土耳其': 'Turkey',
    '圣其茨和尼维斯': 'Saint Kitts and Nevis',
    '圣卢西亚': 'Saint Lucia',
    '圣多美和普林西比': 'Sao Tome and Principle',
    '圣巴泰勒米岛': 'Saint Barthelemy',
    '圣文森特和格林纳丁斯': 'Saint Vincent and the Grenadines',
    '圣皮埃尔和密克隆群岛': 'Saint Pierre and Miquelon',
    '圣马丁岛': 'Saint Martin',
    '圣马力诺': 'San Marino',
    '圭亚那': 'Guyana',
    '坦桑尼亚': 'Tanzania',
    '埃及': 'Egypt',
    '埃塞俄比亚': 'Ethiopia',
    '塔吉克斯坦': 'Tajikistan',
    '塞内加尔': 'Senegal',
    '塞尔维亚': 'Serbia',
    '塞拉利昂': 'Sierra Leone',
    '塞浦路斯': 'Cyprus',
    '塞舌尔': 'Seychelles',
    '墨西哥': 'Mexico',
    '多哥': 'Togo',
    '多米尼克': 'Dominica',
    '多米尼加': 'Dominican Republic',
    '奥地利': 'Austria',
    '委内瑞拉': 'Venezuela',
    '孟加拉国': 'Bangladesh',
    '安哥拉': 'Angola',
    '安圭拉': 'Anguilla',
    '安提瓜和巴布达': 'Antigua & Barbuda',
    '安道尔': 'Andorra',
    '尼加拉瓜': 'Nicaragua',
    '尼日利亚': 'Nigeria',
    '尼日尔': 'Niger',
    '尼泊尔': 'Nepal',
    '巴勒斯坦': 'Palestine',
    '巴哈马': 'Bahamas',
    '巴基斯坦': 'Pakistan',
    '巴巴多斯': 'Barbados',
    '巴布亚新几内亚': 'Papua New Guinea',
    '巴拉圭': 'Paraguay',
    '巴拿马': 'Panama',
    '巴林': 'Bahrain',
    '巴西': 'Brazil',
    '布基纳法索': 'Burkina Faso',
    '布隆迪共和国': 'The Republic of Burundi',
    '希腊': 'Greece',
    '库拉索岛': 'Curaçao',
    '开曼群岛': 'Cayman Islands',
    '德国': 'Germany',
    '意大利': 'Italy',
    '拉脱维亚': 'Latvia',
    '挪威': 'Norway',
    '捷克': 'Czech Republic',
    '摩尔多瓦': 'Republic of Moldova',
    '摩洛哥': 'Morocco',
    '摩纳哥': 'Monaco',
    '文莱': 'Brunei Darussalam',
    '斐济': 'The Republic of Fiji',
    '斯威士兰': 'Swaziland',
    '斯洛伐克': 'Slovakia',
    '斯洛文尼亚': 'Slovenia',
    '斯里兰卡': 'Sri Lanka',
    '新加坡': 'Singapore',
    '新喀里多尼亚': 'New Caledonia',
    '新西兰': 'New Zealand',
    '日本': 'Japan',
    '智利': 'Chile',
    '柬埔寨': 'Cambodia',
    '根西岛': 'Guernsey',
    '格林那达': 'Grenada',
    '格陵兰': 'Greenland',
    '格鲁吉亚': 'Georgia',
    '梵蒂冈': 'Status Civitatis Vaticanae',
    '比利时': 'Belgium',
    '毛里塔尼亚': 'Mauritania',
    '毛里求斯': 'Mauritius',
    '沙特阿拉伯': 'Saudi Arabia',
    '法国': 'France',
    '法属圭亚那': 'French Guiana',
    '法属波利尼西亚': 'French Polynesia',
    '法罗群岛': 'Faroe Islands',
    '波兰': 'Poland',
    '波多黎各': 'Puerto Rico',
    '波黑': 'Bosnia and Herzegovina',
    '泰国': 'Thailand',
    '泽西岛': 'Bailiwick of Jersey',
    '津巴布韦': 'Zimbabwe',
    '洪都拉斯': 'Honduras',
    '海地': 'The Republic of Haiti',
    '澳大利亚': 'Australia',
    '爱尔兰': 'Ireland',
    '爱沙尼亚': 'Estonia',
    '牙买加': 'Jamaica',
    '特克斯和凯科斯群岛': 'Turks and Caicos\xa0Islands',
    '特立尼达和多巴哥': 'Trinidad and Tobago',
    '玻利维亚': 'Bolivia',
    '瑞典': 'Sweden',
    '瑞士': 'Switzerland',
    '瓜德罗普岛': 'Guadeloupe',
    '留尼旺': 'Reunion',
    '白俄罗斯': 'Belarus',
    '百慕大': 'Bermuda',
    '直布罗陀': 'Gibraltar',
    '福克兰群岛': 'Falkland Islands',
    '科威特': 'Kuwait',
    '科摩罗': 'Union des Comores',
    '科特迪瓦': 'Cote d Ivoire',
    '秘鲁': 'Peru',
    '突尼斯': 'Tunisia',
    '立陶宛': 'Lithuania',
    '索马里': 'Somalia',
    '约旦': 'Jordan',
    '纳米比亚': 'Namibia',
    '缅甸': 'Myanmar',
    '罗马尼亚': 'Romania',
    '美国': 'United States of America',
    '美属维尔京群岛': 'United States Virgin Islands',
    '老挝': 'Laos',
    '肯尼亚': 'Kenya',
    '芬兰': 'Finland',
    '苏丹': 'Sudan',
    '苏里南': 'Suriname',
    '英国': 'United Kingdom',
    '英属维尔京群岛': 'British Virgin Islands',
    '荷兰': 'Netherlands',
    '荷兰加勒比地区': 'Bonaire',
    '荷属圣马丁': 'Sint Maarten',
    '莫桑比克': 'Mozambique',
    '菲律宾': 'Philippines',
    '萨尔瓦多': 'The Republic of El Salvador',
    '葡萄牙': 'Portugal',
    '蒙古': 'Mongolia',
    '蒙特塞拉特': 'Montserrat',
    '西班牙': 'Spain',
    '贝宁': 'Benin',
    '赞比亚共和国': 'The Republic of Zambia',
    '赤道几内亚': 'Equatorial Guinea',
    '越南': 'Vietnam',
    '阿塞拜疆': 'Azerbaijan',
    '阿富汗': 'Afghanistan',
    '阿尔及利亚': 'Algeria',
    '阿尔巴尼亚': 'Albania',
    '阿曼': 'Oman',
    '阿根廷': 'Argentina',
    '阿联酋': 'United Arab Emirates',
    '阿鲁巴': 'Aruba',
    '韩国': 'Republic of Korea',
    '马尔代夫': 'Maldives',
    '马恩岛': 'Isle of Man',
    '马拉维': 'Malawi',
    '马提尼克': 'Martinique',
    '马来西亚': 'Malaysia',
    '马约特': 'Mayotte',
    '马耳他': 'Malta',
    '马达加斯加': 'Madagascar',
    '马里': 'Mali',
    '黎巴嫩': 'Lebanon',
    '黑山': 'Montenegro'
 }
